#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinclude
CFLAGS = -Wall -std=c++11
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = lib/libgsharp.a

INC_TEST = $(INC) -Iexternal/gtest/include
CFLAGS_TEST = $(CFLAGS) -g -DTEST_BUILD
RESINC_TEST = $(RESINC)
RCFLAGS_TEST = $(RCFLAGS)
LIBDIR_TEST = $(LIBDIR)
LIB_TEST = $(LIB)external/gtest/lib/libgtest.a external/gtest/lib/libgtest_main.a
LDFLAGS_TEST = $(LDFLAGS) -pthread
OBJDIR_TEST = obj/Test
DEP_TEST = 
OUT_TEST = gsharp_test

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/gsharp.o $(OBJDIR_RELEASE)/src/gsharp_parser.o $(OBJDIR_RELEASE)/src/gsharp_program.o

OBJ_TEST = $(OBJDIR_TEST)/src/gsharp_parser.o $(OBJDIR_TEST)/src/gsharp_program.o $(OBJDIR_TEST)/test/parse_expression_test.o $(OBJDIR_TEST)/test/parse_o_code_test.o

all: release test

clean: clean_release clean_test

before_release: 
	test -d lib || mkdir -p lib
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(AR) rcs $(OUT_RELEASE) $(OBJ_RELEASE)

$(OBJDIR_RELEASE)/src/gsharp.o: src/gsharp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gsharp.cpp -o $(OBJDIR_RELEASE)/src/gsharp.o

$(OBJDIR_RELEASE)/src/gsharp_parser.o: src/gsharp_parser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gsharp_parser.cpp -o $(OBJDIR_RELEASE)/src/gsharp_parser.o

$(OBJDIR_RELEASE)/src/gsharp_program.o: src/gsharp_program.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gsharp_program.cpp -o $(OBJDIR_RELEASE)/src/gsharp_program.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf lib
	rm -rf $(OBJDIR_RELEASE)/src

before_test: 
	test -d $(OBJDIR_TEST)/src || mkdir -p $(OBJDIR_TEST)/src
	test -d $(OBJDIR_TEST)/test || mkdir -p $(OBJDIR_TEST)/test

after_test: 

test: before_test out_test after_test

out_test: before_test $(OBJ_TEST) $(DEP_TEST)
	$(LD) $(LIBDIR_TEST) -o $(OUT_TEST) $(OBJ_TEST)  $(LDFLAGS_TEST) $(LIB_TEST)

$(OBJDIR_TEST)/src/gsharp_parser.o: src/gsharp_parser.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/gsharp_parser.cpp -o $(OBJDIR_TEST)/src/gsharp_parser.o

$(OBJDIR_TEST)/src/gsharp_program.o: src/gsharp_program.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/gsharp_program.cpp -o $(OBJDIR_TEST)/src/gsharp_program.o

$(OBJDIR_TEST)/test/parse_expression_test.o: test/parse_expression_test.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/parse_expression_test.cpp -o $(OBJDIR_TEST)/test/parse_expression_test.o

$(OBJDIR_TEST)/test/parse_o_code_test.o: test/parse_o_code_test.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/parse_o_code_test.cpp -o $(OBJDIR_TEST)/test/parse_o_code_test.o

clean_test: 
	rm -f $(OBJ_TEST) $(OUT_TEST)
	rm -rf $(OBJDIR_TEST)/src
	rm -rf $(OBJDIR_TEST)/test

.PHONY: before_release after_release clean_release before_test after_test clean_test

